'use strict';

require.config({
    urlArgs: 'd=' + Date.now(),
    waitSeconds: 0,
    paths: {
        'domReady': 'lib/bower_components/domReady/domReady',
        'jquery': 'lib/bower_components/jquery/dist/jquery.min',
        'svg-morpheus': 'lib/bower_components/svg-morpheus/compile/minified/svg-morpheus',
        'chart': 'lib/bower_components/Chart.js/Chart',
        'angular': 'lib/bower_components/angular/angular.min',
        'ngAnimate': 'lib/bower_components/angular-animate/angular-animate.min',
        'ngAria': 'lib/bower_components/angular-aria/angular-aria.min',
        'angular-chart': 'lib/bower_components/angular-chart.js/dist/angular-chart.min',
        'ngMaterial': 'lib/bower_components/angular-material/angular-material.min',
        'ngMdIcons': 'lib/bower_components/angular-material-icons/angular-material-icons.min',
        'ngMessages': 'lib/bower_components/angular-messages/angular-messages.min',
        'ngRoute': 'lib/bower_components/angular-route/angular-route.min',
        'angular-ui-mask' : 'lib/bower_components/angular-ui-mask/src/mask',
        'ngSanitize': 'lib/bower_components/angular-sanitize/angular-sanitize.min',
        'angular-locale_ru-ru': 'lib/bower_components/angular-i18n/angular-locale_ru-ru',
        'angular-spinkit': 'lib/bower_components/angular-spinkit/build/angular-spinkit.min',
        'ngFileSaver': 'lib/bower_components/angular-file-saver/dist/angular-file-saver.bundle.min',
        'pascalprecht.translate': 'lib/bower_components/angular-translate/angular-translate.min',
        'angular-translate-loader-partial': 'lib/bower_components/angular-translate-loader-partial/angular-translate-loader-partial.min',
        'md.data.table': 'lib/bower_components/angular-material-data-table/dist/md-data-table.min',
        'ui.tree': 'lib/bower_components/angular-ui-tree/dist/angular-ui-tree.min',
        'ngCookies': 'lib/bower_components/angular-cookies/angular-cookies.min',
        'angular-notification-icons': 'lib/bower_components/angular-notification-icons/dist/angular-notification-icons.min',
        'angular-local-storage': 'lib/bower_components/angular-local-storage/dist/angular-local-storage.min',
        'sockjs-client': 'lib/bower_components/sockjs-client/dist/sockjs-1.1.1.min',
        'stomp-websocket': 'lib/bower_components/stomp-websocket/lib/stomp.min',
        'petrovich': 'lib/bower_components/petrovich/dist/petrovich.min',
        'ngFileUpload': 'lib/bower_components/ng-file-upload/ng-file-upload.min',
        'webcam': 'lib/bower_components/webcam-directive/dist/webcam.min',
        'ngImgCrop': 'lib/bower_components/ng-img-crop/compile/minified/ng-img-crop',
        'angular-simple-logger': "lib/bower_components/angular-simple-logger/dist/angular-simple-logger.min",
        'leaflet': 'lib/bower_components/leaflet/dist/leaflet',
        'ui-leaflet': 'lib/bower_components/ui-leaflet/dist/ui-leaflet.min',
        'leaflet-google': 'lib/bower_components/leaflet-plugins/layer/tile/Google',
        'leaflet-yandex': 'lib/bower_components/leaflet-plugins/layer/tile/Yandex',
        'kladr': 'lib/bower_components/jquery.kladr/jquery.kladr.min',
        'moment': 'lib/bower_components/moment/min/moment.min',
        'mdPickers': 'lib/bower_components/mdPickers/dist/mdPickers.min',
        'tinymce': 'lib/bower_components/tinymce-dist/tinymce.min',
    },
    shim: {
        'svg-morpheus': {exports: 'SVGMorpheus'},
        'angular': {exports: 'angular'},
        'angular-locale_ru-ru': {deps: ['angular']},
        'ngRoute': {deps: ['angular']},
        'angular-ui-mask':  {deps: ['angular']},
        'ngCookies': {deps: ['angular']},
        'ngAnimate': {deps: ['angular']},
        'ngSanitize': {deps: ['angular']},
        'ngMessages': {deps: ['angular']},
        'ngAria': {deps: ['angular']},
        'angular-spinkit': {deps: ['angular']},
        'ngMdIcons': {deps: ['angular', 'svg-morpheus']},
        'pascalprecht.translate': {deps: ['angular']},
        'angular-translate-loader-partial': {deps: ['angular', 'pascalprecht.translate']},
        'ngMaterial': {deps: ['angular']},
        'ngFileSaver': {deps: ['angular']},
        'md.data.table': {deps: ['angular']},
        'ui.tree': {deps: ['angular']},
        'angular-notification-icons': {deps: ['angular']},
        'angular-local-storage': {deps: ['angular']},
        'sockjs-client': {exports: 'SockJS'},
        'stomp-websocket': {exports: 'Stomp', deps: ['sockjs-client']},
        'petrovich': {exports: 'petrovich'},
        'ngFileUpload': {deps: ['angular']},
        'webcam': {deps: ['angular']},
        'ngImgCrop': {deps: ['angular']},
        'angular-simple-logger': {deps: ['angular']},
        'ui-leaflet': {deps: ['angular', 'leaflet', 'angular-simple-logger']},
        'leaflet-google': {deps: ['leaflet']},
        'leaflet-yandex': {deps: ['leaflet']},
        'kladr': {deps: ['jquery']},
        'mdPickers': {deps: ['angular', 'moment']},
        'tinymce': {deps: ['jquery'], exports: 'tinymce'},
        'chart': {exports: 'Chart'},
    }
});

require([
    'require',
    'angular',
    'angular-locale_ru-ru',
    'ngRoute',
    'ngCookies',
    'ngAnimate',
    'ngSanitize',
    'ngMessages',
    'ngAria',
    'angular-spinkit',
    'ngMdIcons',
    'angular-chart',
    'pascalprecht.translate',
    'angular-translate-loader-partial',
    'ngMaterial',
    'ngFileSaver',
    'md.data.table',
    'ui.tree',
    'angular-chart',
    'angular-notification-icons',
    'angular-local-storage',
    'sockjs-client',
    'stomp-websocket',
    'jquery',
    'petrovich',
    'ngFileUpload',
    'ngImgCrop',
    'webcam',
    'angular-simple-logger',
    'leaflet',
    'leaflet-google',
    'leaflet-yandex',
    'ui-leaflet',
    'kladr',
    'mdPickers',
    'tinymce',
    'angular-ui-mask',
    'app',
    'components/app-directives',
    'components/app-filters',
    'components/app-services',
    'components/app-controllers',
    'components/config/config',
    'components/debug/debug',
    'components/debug/debug-controllers',
    'components/dialogs/dialogs',
    'components/dialogs/dialogs-controllers',
    'components/navigation/navigation',
    'components/navigation/navigation-services',
    'components/navigation/navigation-controllers',
    'components/page/page',
    'components/page/page-services',
    'components/page/page-controllers',
    'components/stomp/stomp',
    'components/stomp/stomp-services',
    'components/stomp/stomp-controllers',
    'components/stream_tabs/stream-tabs',
    'components/choose-photo/choose-photo',
    'components/geo/geo',
    'components/geo/geo-directives',
    'components/geo/geo-services',
    'components/timetable/timetable',
    'components/timetable/timetable-services',
    'components/timetable/timetable-directives',
    'components/passport/passport',
    'components/passport/passport-services',
    'components/passport/passport-directives',
    'components/fields/visibility/visibility-directives',
    'components/fields/visibility/visibility-services',
    'components/fields/visibility/visibility'
], function (require, angular) {
    require(['domReady!'], function (document) {
        angular.bootstrap(document, ['blagosfera']);
    });
});