package ru.radom.kabinet.module.rameralisteditor;

/**
 * Created by vgusev on 02.06.2015.
 */
public enum RameraListEditorActionType {
    ADD_RAMERA_LIST_EDITOR, UPDATE_RAMERA_LIST_EDITOR, DELETE_RAMERA_LIST_EDITOR, GET_RAMERA_LIST_EDITOR_BY_NAME, GET_RAMERA_LIST_EDITOR_WITH_CHILDS_BY_NAME, GET_ALL_RAMERA_LIST_EDITORS,
    ADD_RAMERA_LIST_EDITOR_ITEM, UPDATE_RAMERA_LIST_EDITOR_ITEM, DELETE_RAMERA_LIST_EDITOR_ITEM, GET_RAMERA_LIST_EDITOR_ITEM_BY_NAME;
}
