package ru.radom.kabinet.utils;

import java.util.HashSet;
import java.util.Set;

public class Roles {
	public static final String ROLE_ADMIN = "ROLE_ADMIN";
	public static final String ROLE_SUPERADMIN = "ROLE_SUPERADMIN";

	public static final String ROLE_REGISTRATOR_REGISTRATORS_EDITOR = "ROLE_REGISTRATOR_REGISTRATORS_EDITOR";
	public static final String ROLE_REGISTRATOR_COMMUNITIES_EDITOR = "ROLE_REGISTRATOR_COMMUNITIES_EDITOR";
	public static final String ROLE_REGISTRATOR_SHARERS_EDITOR = "ROLE_REGISTRATOR_SHARERS_EDITOR";
	
	public static final Set<String> REGISTRATOR_ROLES = new HashSet<>();
	
	static {
		REGISTRATOR_ROLES.add(ROLE_REGISTRATOR_REGISTRATORS_EDITOR);
		REGISTRATOR_ROLES.add(ROLE_REGISTRATOR_COMMUNITIES_EDITOR);
		REGISTRATOR_ROLES.add(ROLE_REGISTRATOR_SHARERS_EDITOR);
	}
	
	public static final String ROLE_BLAGOSFERA_MENU_EDITOR = "ROLE_BLAGOSFERA_MENU_EDITOR";
	public static final String ROLE_BLAGOSFERA_PAGES_EDITOR = "ROLE_BLAGOSFERA_PAGES_EDITOR";
	public static final String ROLE_BLAGOSFERA_SHARERS_DELETER = "ROLE_BLAGOSFERA_SHARERS_DELETER";
	public static final String ROLE_BLAGOSFERA_NEWS_WRITER = "ROLE_BLAGOSFERA_NEWS_WRITER";
	
	public static final Set<String> BLAGOSFERA_ROLES = new HashSet<>();
		
	static {
		BLAGOSFERA_ROLES.add(ROLE_BLAGOSFERA_MENU_EDITOR);
		BLAGOSFERA_ROLES.add(ROLE_BLAGOSFERA_PAGES_EDITOR);
		BLAGOSFERA_ROLES.add(ROLE_BLAGOSFERA_SHARERS_DELETER);
		BLAGOSFERA_ROLES.add(ROLE_BLAGOSFERA_NEWS_WRITER);
	}
}