//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.29 at 12:53:11 PM MSK 
//


package ru.askor.blagosfera.domain.xml.cashbox;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.askor.blagosfera.domain.xml.cashbox package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.askor.blagosfera.domain.xml.cashbox
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdatePricesRequest }
     * 
     */
    public UpdatePricesRequest createUpdatePricesRequest() {
        return new UpdatePricesRequest();
    }

    /**
     * Create an instance of {@link ImportProductsRequest }
     * 
     */
    public ImportProductsRequest createImportProductsRequest() {
        return new ImportProductsRequest();
    }

    /**
     * Create an instance of {@link OperatorStopResponse }
     * 
     */
    public OperatorStopResponse createOperatorStopResponse() {
        return new OperatorStopResponse();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Basket }
     * 
     */
    public Basket createBasket() {
        return new Basket();
    }

    /**
     * Create an instance of {@link OperatorStopResponse.Products }
     * 
     */
    public OperatorStopResponse.Products createOperatorStopResponseProducts() {
        return new OperatorStopResponse.Products();
    }

    /**
     * Create an instance of {@link ImportProductsRequest.Products }
     * 
     */
    public ImportProductsRequest.Products createImportProductsRequestProducts() {
        return new ImportProductsRequest.Products();
    }

    /**
     * Create an instance of {@link UpdatePricesRequest.Products }
     * 
     */
    public UpdatePricesRequest.Products createUpdatePricesRequestProducts() {
        return new UpdatePricesRequest.Products();
    }

    /**
     * Create an instance of {@link OperatorStartRequest }
     * 
     */
    public OperatorStartRequest createOperatorStartRequest() {
        return new OperatorStartRequest();
    }

    /**
     * Create an instance of {@link AcceptExchangeResponse }
     * 
     */
    public AcceptExchangeResponse createAcceptExchangeResponse() {
        return new AcceptExchangeResponse();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link OperatorStartResponse }
     * 
     */
    public OperatorStartResponse createOperatorStartResponse() {
        return new OperatorStartResponse();
    }

    /**
     * Create an instance of {@link AcceptRegistrationResponse }
     * 
     */
    public AcceptRegistrationResponse createAcceptRegistrationResponse() {
        return new AcceptRegistrationResponse();
    }

    /**
     * Create an instance of {@link AcceptExchangeRequest }
     * 
     */
    public AcceptExchangeRequest createAcceptExchangeRequest() {
        return new AcceptExchangeRequest();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link OperatorStopRequest }
     * 
     */
    public OperatorStopRequest createOperatorStopRequest() {
        return new OperatorStopRequest();
    }

    /**
     * Create an instance of {@link RegisterResponse }
     * 
     */
    public RegisterResponse createRegisterResponse() {
        return new RegisterResponse();
    }

    /**
     * Create an instance of {@link RegisterRequest }
     * 
     */
    public RegisterRequest createRegisterRequest() {
        return new RegisterRequest();
    }

    /**
     * Create an instance of {@link ExchangeRequest }
     * 
     */
    public ExchangeRequest createExchangeRequest() {
        return new ExchangeRequest();
    }

    /**
     * Create an instance of {@link UpdatePricesResponse }
     * 
     */
    public UpdatePricesResponse createUpdatePricesResponse() {
        return new UpdatePricesResponse();
    }

    /**
     * Create an instance of {@link ImportProductsResponse }
     * 
     */
    public ImportProductsResponse createImportProductsResponse() {
        return new ImportProductsResponse();
    }

    /**
     * Create an instance of {@link SessionCheckResponse }
     * 
     */
    public SessionCheckResponse createSessionCheckResponse() {
        return new SessionCheckResponse();
    }

    /**
     * Create an instance of {@link AcceptRegistrationRequest }
     * 
     */
    public AcceptRegistrationRequest createAcceptRegistrationRequest() {
        return new AcceptRegistrationRequest();
    }

    /**
     * Create an instance of {@link IdentificationResponse }
     * 
     */
    public IdentificationResponse createIdentificationResponse() {
        return new IdentificationResponse();
    }

    /**
     * Create an instance of {@link ShareHolder }
     * 
     */
    public ShareHolder createShareHolder() {
        return new ShareHolder();
    }

    /**
     * Create an instance of {@link IdentificationRequest }
     * 
     */
    public IdentificationRequest createIdentificationRequest() {
        return new IdentificationRequest();
    }

    /**
     * Create an instance of {@link ExchangeResponse }
     * 
     */
    public ExchangeResponse createExchangeResponse() {
        return new ExchangeResponse();
    }

    /**
     * Create an instance of {@link SessionCheckRequest }
     * 
     */
    public SessionCheckRequest createSessionCheckRequest() {
        return new SessionCheckRequest();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link Payment.Cash }
     * 
     */
    public Payment.Cash createPaymentCash() {
        return new Payment.Cash();
    }

    /**
     * Create an instance of {@link Payment.Nocash }
     * 
     */
    public Payment.Nocash createPaymentNocash() {
        return new Payment.Nocash();
    }

    /**
     * Create an instance of {@link Basket.Item }
     * 
     */
    public Basket.Item createBasketItem() {
        return new Basket.Item();
    }

    /**
     * Create an instance of {@link OperatorStopResponse.Products.Product }
     * 
     */
    public OperatorStopResponse.Products.Product createOperatorStopResponseProductsProduct() {
        return new OperatorStopResponse.Products.Product();
    }

    /**
     * Create an instance of {@link ImportProductsRequest.Products.Product }
     * 
     */
    public ImportProductsRequest.Products.Product createImportProductsRequestProductsProduct() {
        return new ImportProductsRequest.Products.Product();
    }

    /**
     * Create an instance of {@link UpdatePricesRequest.Products.Product }
     * 
     */
    public UpdatePricesRequest.Products.Product createUpdatePricesRequestProductsProduct() {
        return new UpdatePricesRequest.Products.Product();
    }

}
